
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-6 pull-right">
	<div class="dashboard-stat blue">
	    <div class="visual">
	            <i class="fa fa-comments"></i>
	        </div>
	        <div class="details">
	            <div class="number">
	                <span data-counter="counterup" data-value="<?=$num_customers;?>">0</span>
	            </div>

	        <div class="desc"> Total Customers </div>
	    </div>
	    <a class="more" href="javascript:;"> View more
	        <i class="m-icon-swapright m-icon-white"></i>
	    </a>
	</div>
</div>

<h3 class='page-title'>Customers <br /><small>List of customers</small></h3>	


<?php 
if(!empty($flashMessages)){
	foreach($flashMessages as $message){
		echo "<p>{$message}</p>";
	}
}?>

<table class="table table-hover">
      <thead>
        <tr>
          <th>Company</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      
<?php 
foreach($customers as $customer):?>
        <tr>
          <td><?=$customer->company_name; ?></td>
          <td><?=$customer->fname . ' ' . $customer->lname;?></td>
	         <td>
	         	<a href="/user/account/list?id=<?=$customer->id?>">
	          		<span class="glyphicon glyphicon-cog"></span>
	         	</a>
	          	<a href="/user/account/delete?id=<?=$customer->id?>">
				  	<span class="glyphicon glyphicon-remove"></span>
				</a>
			</td>
        </tr>
<?php endforeach; ?>      

	</tbody>
</table>

</div>