
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	    <div class="dashboard-stat blue">
	        <div class="visual">
	            <i class="fa fa-comments"></i>
	        </div>
	        <div class="details">
	            <div class="number">
	                <span data-counter="counterup" data-value="1349">0</span>
	            </div>
	            <div class="desc"> Customers </div>
	        </div>
	        <a class="more" href="javascript:;"> View more
	            <i class="m-icon-swapright m-icon-white"></i>
	        </a>
	    </div>
	</div>


<table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Username</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Gene</td>
          <td>Goodreau</td>
          <td>gene@marketboss.ca</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Trevor</td>
          <td>Sean</td>
          <td>trevor@marketboss.ca</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Clayton</td>
          <td>Reid</td>
          <td>clayton@marketboss.ca</td>
        </tr>
      </tbody>
</table>

</div>

                  
