<?= $this->message; ?>

<h1>Add User</h1>

<?php 
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);?>

<fieldset>

<?php
foreach($this->form1 as $element):
	if(!($element instanceof Zend\Form\Form\Element\Sbumit)):?>
	
	<div class='control-group'>
		<label class='control-label' for="<?= $element->getName();?>"><?= $element->getLabel(); ?></label>
		
		<div class='controls'>
			<?= $this->formElement($element); ?>
			<?= $this->formElementErrors($element); ?>
		</div>
	</div>

<?php endif; endforeach; ?>

<div class='form-actions'>

</div>

</fieldset>

<?php echo $this->form()->closeTag();?>