<?php echo $this->doctype(); session_start();?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Eco Enterprise - Homepage</title>
<?php include_once($_SERVER['DOCUMENT_ROOT'] . '/template/includes.php'); ?>
</head>

<body id="home">
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href='/h/homepage.php'><img src="/images/layout/logo.png" alt="Eco Enterprise Homepage" width='75px'/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <?php
$homepage = "<li><a href='/h/homepage.php'>HOME</a></li>";

$management = "
	<li class='dropdown'>
		<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>MANAGEMENT<span class='caret'></span></a>
		<ul class='dropdown-menu' role='menu'>
			<li><a href='/h/reports/index.php'>REPORTS</a></li>
			<li><a href='/h/franchises/franchise_manager.php'>FRANCHISES</a></li>
	  	  </ul>
	 </li>
";


$establishment = "
	<li class='dropdown'>
		<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>ESTABLISHMENT<span class='caret'></span></a>
		<ul class='dropdown-menu' role='menu'>
			<li><a href='/h/my_eco/my_eco.php'>MY ECO</a></li>
       		<li><a href='/employee'>EMPLOYEES</a></li>
      		<li><a href='/h/resources/resources.php'>RESOURCES</a></li>
      		<li><a href='/h/documents/documents.php'>DOCUMENTS</a></li>
	  	  </ul>
	 </li>
";

$sales = "
	<li class='dropdown'>
		<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>SALES<span class='caret'></span></a>
		<ul class='dropdown-menu' role='menu'>
			<li><a href='/h/calendar/index.php'>CALENDAR</a></li>
			<li><a href='/h/quote/index.php'>NEW RFQ</a></li>
       		<li><a href='/h/customer/index.php'>CUSTOMERS</a></li>
      		<li><a href='/h/project/projects.php'>PROJECTS</a></li>
	  	  </ul>
	 </li>
";

$operations = "
	<li class='dropdown'>
		<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>OPERATIONS<span class='caret'></span></a>
		<ul class='dropdown-menu' role='menu'>
			<li><a href='/h/dispatch/dispatch.php'>DISPATCH</a></li>
			<li><a href='/h/calendar/index.php'>CALENDAR</a></li>
       		<li><a href='/h/resources/resources.php'>RESOURCES</a></li>
      		<li><a href='/h/project/projects.php'>PROJECTS</a></li>
	  	  </ul>
	 </li>
";

$finance = "
	<li class='dropdown'>
		<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>FINANCE<span class='caret'></span></a>
		<ul class='dropdown-menu' role='menu'>
			<li><li><a href='/h/product/product_manager.php'>PRODUCTS</a></li></li>
			<li><a href='/h/commissions/index.php'>COMMISSIONS</a></li>
       		<li><a href='/h/accts_receivable/accts_receivable.php'>ACCNTS. REC.</a></li>
	  	  </ul>
	 </li>
";



$quote = "<li><a href='/h/quote/index.php'>NEW RFQ</a></li>";
$cal = "<li><a href='/h/calendar/index.php'>CALENDAR</a></li>"; 
$cust = "<li><a href='/h/customer/index.php'>CUSTOMERS</a></li>";
$proj = "<li><a href='/h/project/projects.php'>PROJECTS</a></li>";
$disp = "<li><a href='/h/dispatch/dispatch.php'>DISPATCH</a></li>";

$my_eco = "<li><a href='/h/my_eco/my_eco.php'>MY ECO</a></li>";
$reports = "<li><a href='/h/reports/index.php'>REPORTS</a></li>";
$documents = "<li><a href='/h/documents/documents.php'>DOCUMENTS</a></li>";

$empl = "<li class='dropdown'>
			<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>ESTABLISHMENT<span class='caret'></span></a>
			<ul class='dropdown-menu' role='menu'>
	       		<li><a href='/h/employees/index.php'>EMPLOYEES</a></li>
	      		<li><a href='/h/resources/resources.php'>RESOURCES</a></li>
		  	  </ul>
		 </li>";

$accts_rec = "<li><a href='/h/accts_receivable/accts_receivable.php'>ACCNTS. REC.</a></li>";
$products = "<li><a href='/h/product/product_manager.php'>PRODUCTS</a></li>";
$commissions = "<li><a href='/h/commissions/index.php'>COMMISSIONS</a></li>";
$franchises = "<li><a href='/h/franchises/franchise_manager.php'>FRANCHISES</a></li>";

$management = array(
	$homepage,
	$management,
	$establishment,
	$sales,
	$operations,
	$finance
);

$dispatch = array(
	$homepage,
	$quote,
	$cal,
	$cust,
	$proj,
	$disp,
	$empl,
	$my_eco,
	$documents,
	$accts_rec
);

$estimator = array(
	$homepage,
	$quote,
	$cal,
	$cust,
	$proj,
	$my_eco,
	$documents
);
$leadhand = array(
	$homepage,
	$cal,
	$cust,
	$proj,
	$my_eco,
	$documents
);

$technician = array(
	$homepage,
	$cal,
	$my_eco,
	$documents
);

if($_SESSION['company_id']==1){
	$management[] = $franchises;
}
/* switch($user->access_level){ */
switch($_SESSION['user']['access_level']){
	case "management": $toolbar = $management; break;
	case "dispatch": $toolbar = $dispatch; break;
	case "estimator": $toolbar = $estimator; break;
	case "lead hand": $toolbar = $leadhand; break;
	case "technician": $toolbar = $technician; break;
	default: $toolbar = false;
}
if(!empty($toolbar)){
	foreach($toolbar as $item){
		echo $item;
	}
}
?>
		<li><a href='/h/logout.php'>
      			LOGOUT</a></li>
      </ul>
	  <!-- <span class='pull-left pull-top' style='color: white;'><strong>Welcome, <?php echo $user->name; ?></strong>  &nbsp;&nbsp;-&nbsp;&nbsp;  <?php echo date('l, F j, Y '); ?></span> -->

        <form class="navbar-form navbar-right" 
        	role="search"
        	action="/h/locator/locator.php" 
        	method="post" 
        	name="locator"
        >


				<input name="query" type="text" class="input" />
		            <select name="locate_by"  class="form-control">
		            <?php if($user->access_level == "technician"){?>
		            	<option value="job_num">Job Number</option>
		            <?php }elseif($user->access_level == "lead hand"){?>
		            	<option value='workorder'>Workorder</option>
		            	<option value="estimate_num">Project Number</option>
		            	<option value="job_num">Job Number</option>
		            	<option value='job_location'>Install Address</option>
		            <?php } else {?>
		            	
		            	<option value="customer_name">Customer Name</option>
		            	<option value="estimate_num">Project Number</option>
		            	<option value='workorder'>Workorder</option>
		            	<option value="customer_phone">Customer Phone</option>
		            	<option value="invoice_num">Invoice Number</option>
		            	<option value="job_num">Job Number</option>
		            	<option value='job_location'>Install Address</option>
		            <?php } ?>
		            </select>

            
					<input name="locate" type="submit" value="Search" class="btn btn-default"/>
        	
            </form> 
		</div>

      <!--
<ul class="nav navbar-nav navbar-right">
      	<li>
      		      	</li>
      </ul>
-->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>		

<div id="content" class="group container-fluid">
	<?php
		echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-info'));
?>
			<?php echo $this->content; ?>
		</div>
    </body>
</html>
